config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/home', to: 'dashboard#home'
  get 'certification/:run' , to: 'dashboard#student_certification', as:'certification', :defaults=>{ :format => 'pdf'}
  get 'diploma/:run' , to: 'dashboard#student_diploma', as:'diploma', :defaults=>{ :format => 'pdf'}
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :courses
  resources :students

  root to: 'dashboard#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
before_action :set_student, only: %i[ student_certification student_diploma]
  def home
    @existe = true
    if params[:run].present?
      @student = Student.where("run = ?", params[:run])
      if @student.empty?
        @existe = false
      end
    end
  end

  def student_certification
    if !@student.empty? || !@stundet.nil?
     
      respond_to do |format|
        format.pdf do 
          render pdf: "Certificado",
            template: 'dashboard/pdf',
            page_size: 'A4',
            margin:  {   top: 10,
              bottom: 10,
              left: 20,
              right: 20}
        end
      end
    else
      respond_to do |format|
        format.pdf { redirect_to root_path, alert: "Error al cargar pdf verifique su run." }
      end
    end  
  end
  def student_diploma
    if !@student.empty? || !@stundet.nil?
     
      respond_to do |format|
        format.pdf do 
          render pdf: "Diploma",
            template: 'dashboard/diplo',
            page_size: 'A4',
            orientation:'Landscape' ,
            margin:  {   top: 10,
              bottom: 10,
              left: 20,
              right: 20}
        end
      end
    else
      respond_to do |format|
        format.pdf { redirect_to root_path, alert: "Error al cargar pdf verifique su run." }
      end
    end  
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.where("run = ?", params[:run])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_form.html.erb
<form class="ui large form">
    <div class="ui stacked segment">
        <div class="field">
            <div class="ui left icon input">
                <i class="search icon"></i>
                <input type="search" placeholder="10111222-5" aria-label="Search" name="run">
            </div>
        </div>
        <div class="field">
            <button class="ui fluid large teal submit button" type="submit">Search</button>
        </div>
    <div class="ui pointing teal basic label">
        Porfavor ingrese su run con guión y sin punto.
      </div>
    </div>
</form>

app/views/dashboard/diplo.pdf.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8">
    <title>Certificación</title>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,300;0,400;1,400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
  </head>
<%= wicked_pdf_stylesheet_link_tag 'diplo'%>
  <body>
    <header>
        <%= image_tag wicked_pdf_asset_base64('logo-cbcl.jpg') %>
    </header>
    <h1>cbcl chile</h1>
    <div class="content-diplo">
     <% @student.each do |student| %>
        <p>Centro de Capacitación y Formación Bancaria de Chile</p>
<p>En el cumplimiento al Plan de Estudio impartido por esta institución, se otorga el siguiente diploma a:</p>
            <h3><%= student.name %></h3>
            <h4>RUT: <%= student.run %></h4>
        <p>Quien ha aprobado satisfactoriamente la capacitación de:</p>
            <h2>Cajero Bancario en <%= student.courses.map(&:name).join('y ')  %></h2>
        <p>Extendiéndose el presente de acuerdo a las disposiciones legales vigentes.</p>
    
    <div class="firm">
        <%= image_tag wicked_pdf_asset_base64("selloyfirmaCBCL.png") %>
        <div class="director">
            <div class="line"></div>
            <p>Gonzalo Gálves Fuetes</p>
            <p>Director Académico</p>
        </div>
    </div>
    <% end %>
    
    </div>
    <footer>
        <a href="mailto:coordinacion@cbclvirtual.cl">CBCL - París 838, of. 305, 306, piso 2, Santiago. coordinacion@cbclvirtual.cl</a>
    </footer>
  </body>
</html>

app/views/dashboard/home.html.erb
<div class="ui middle aligned center aligned grid h-100 bg-one">
    <div class="row">
      <div class="five wide column">
    <%=image_tag 'logo-cbcl.jpg', class:"image" %>
  <div class="ui teal header">
    <h1 class="content">Obtención de Certificados</h1>
  </div>
        <%= render 'form'%>
      </div>      
    </div>      
     <%if @student.nil? && @existe%>
      <% elsif @student && !@existe %>
        
          <div class="ui negative message h-fit">
            <i class="close icon"></i>
            <div class="header">
              Estudiante no encontrado.
            </div>
            <p>Verifique su run</p>
          </div>
        
      <% else %>
       <div class="ui top attached w-75">
       
              <table class="ui teal celled table">
                <thead>
                  <tr><th>NOMBRE</th>
                  <th>RUN</th>
                  <th>EMAIL</th>
                  <th>GENERACIÓN</th>
                  <th>CERTIFICACIÓN</th>
                </tr></thead>
                <tbody>
                  <% @student.each do |student| %>
                      <tr>
                      <td data-label="NOMBRE"><%=student.name%></td>
                      <td data-label="RUN"><%=student.run%></td>
                      <td data-label="EMAIL"><%=student.email%></td>
                      <td data-label="GENERACIÓN"><%=student.generation%></td>
                      <td data-label="CERTIFICACIÓN">
                        <%= link_to(certification_path(student.run),class:"ui right labeled olive inverted icon button") do%>
                            Certificación<i class="download icon"></i>
                        <% end %>
                        <%= link_to(diploma_path(student.run),class:"ui right labeled green inverted icon button") do%>
                            Diploma<i class="download icon"></i>
                        <% end %>
                        </td>
                      </tr>
                    
                  <% end %>
                </tbody>
              </table>
        </div>      
      <% end %>
</div>
    
     

app/views/dashboard/pdf.pdf.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8">
    <title>Certificación</title>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,300;0,400;1,400&display=swap" rel="stylesheet">
  </head>
<%= wicked_pdf_stylesheet_link_tag 'pdf'%>
  <body>
    <header>
        <%= image_tag wicked_pdf_asset_base64('logo-cbcl.jpg') %>
    </header>
    <h1>Certificado</h1>
    <div class="content">
     <% @student.each do |student| %>
        <p>C.B.C.L CHILE, Centro de Capacitación y Formación Bancaria de Chile, certifica que </p>
            <h3><%= student.name %>, RUT <%= student.run %></h3>
        <p>ha realizado el curso:</p>
            <h3>Cajero Bancario en <%= student.courses.map(&:name).join(' y ')  %></h3>
        <p>cumpliendo con el correspondiente Plan de Estudio del Programa Especial de
        Inserción Laboral, contemplado en los estatutos de nuestra institución de
        capacitación, obteniendo aprobación satisfactoria en las evaluaciones del curso.</p>
        
        <p>El curso Cajero Bancario en Moneda Nacional y Extranjera, fueron aprobados
        el día <%=student.end_date%>, teniendo una duración de 30 días calendario.</p>
        
        <p>Se extiende el presente certificado a petición del interesado, para los fines que
        estime conveniente.</p>
    
    <div class="firm">
        <%= image_tag wicked_pdf_asset_base64("selloyfirmaCBCL.png") %>
        <div class="director">
            <div class="line"></div>
            <p>Gonzalo Gálves Fuetes</p>
            <p>Director Académico</p>
        </div>
    </div>
    <% end %>
    
    </div>
    <footer>
        <a href="mailto:coordinacion@cbclvirtual.cl">CBCL - París 838, of. 305, 306, piso 2, Santiago. coordinacion@cbclvirtual.cl</a>
    </footer>
  </body>
</html>